|-> error(message, exitCode?) {
    print("Error!", message)
    print(__CALL_STACK)
    process.exit(exitCode ! 5)
}