|-> error(reason) {
    print("Unexpected exit due to error:", reason)
}

error("Hello World")